### ISSUE TITLE
Binary incompatibilities in maven-library used by sbt-native-packager and sbt-pom-reader

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-pom-reader#20]
This is a recent error, triggered by some combination of SBT version or other plugins.  I've been using this plugin as a part of a larger project for a long time, and only had the error triggered when trying to use sbt-native-packager.

It doesn't seem to happen when building the project that uses the plugin independently, but when it serves as a sub-project in a larger muti-project build.

I note that the referenced class is part of `maven-aether-provider`.

Interested in knowing what additional info I can provide to help identify the issue further. 
## Backtrace

``` java
java.lang.NoClassDefFoundError: org/apache/maven/repository/internal/MavenServiceLocator
    at com.typesafe.sbt.pom.package$.newRepositorySystemImpl(package.scala:23)
    at com.typesafe.sbt.pom.MvnPomResolver$.<init>(MavenPomResolver.scala:20)
    at com.typesafe.sbt.pom.MvnPomResolver$.<clinit>(MavenPomResolver.scala)
    at com.typesafe.sbt.pom.package$.loadEffectivePom(package.scala:41)
    at com.typesafe.sbt.pom.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:119)
    at com.typesafe.sbt.pom.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:47)
    at com.typesafe.sbt.pom.PomBuild$class.projectDefinitions(PomBuild.scala:18)
    at MavenBuild$.projectDefinitions(build.scala:2)
    at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
```
## SBT Info

```
[info] This is sbt 0.13.7
[info] The current project is {file:/Users/sfitch/Coding/foo/}bar 2.1-SNAPSHOT
[info] The current project is built against Scala 2.11.4
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbtmeow.SbtMeowPlugin, diagram.Plugin, com.typesafe.sbt.SbtGit, sbtbuildinfo.Plugin, com.typesafe.sbt.SbtScalariform, net.virtualvoid.sbt.graph.Plugin, com.typesafe.sbt.pom.PomReaderPlugin, com.typesafe.sbteclipse.plugin.EclipsePlugin, org.sbtidea.SbtIdeaPlugin, sbtrelease.ReleasePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

**Comment by metasim** [comment]
I tried adding the following to my `project/plugins.sbt`, but still get the error.

```scala
libraryDependencies += "org.apache.maven" % "maven-aether-provider" % "3.2.5"
```

**Comment by metasim** [comment]
I should have provided the full backtrace, as there's a wrapped exception (`ClassNotFoundException`):

```java
java.lang.NoClassDefFoundError: org/apache/maven/repository/internal/MavenServiceLocator
	at com.typesafe.sbt.pom.package$.newRepositorySystemImpl(package.scala:23)
	at com.typesafe.sbt.pom.MvnPomResolver$.<init>(MavenPomResolver.scala:20)
	at com.typesafe.sbt.pom.MvnPomResolver$.<clinit>(MavenPomResolver.scala)
	at com.typesafe.sbt.pom.package$.loadEffectivePom(package.scala:41)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:119)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:47)
	at com.typesafe.sbt.pom.PomBuild$class.projectDefinitions(PomBuild.scala:18)
	at MavenBuild$.projectDefinitions(build.scala:2)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.repository.internal.MavenServiceLocator
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.typesafe.sbt.pom.package$.newRepositorySystemImpl(package.scala:23)
	at com.typesafe.sbt.pom.MvnPomResolver$.<init>(MavenPomResolver.scala:20)
	at com.typesafe.sbt.pom.MvnPomResolver$.<clinit>(MavenPomResolver.scala)
	at com.typesafe.sbt.pom.package$.loadEffectivePom(package.scala:41)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:119)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:47)
	at com.typesafe.sbt.pom.PomBuild$class.projectDefinitions(PomBuild.scala:18)
	at MavenBuild$.projectDefinitions(build.scala:2)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by dwalend** [comment]
I'm seeing the same problem. No great thoughts beyond your own idea for adding the dependency.

**Comment by jsuereth** [comment]
sbt-native-packager pulls in an incompatible version of maven (because it was a jdeb dependency).  I *think* this should be fixed if you can get one of the newer version (like the 1.0.0-RCs).   Not positive.  If you're not using JDeb, I think you may be able to exclude the dependency, let me look into that.

**Comment by metasim** [comment]
Thanks @jsuereth. Back when I had the problem I just ended up converting the sub-project to first-class SBT and forgot about it. Good call with `sbt-native-packager`. I should have realized the problem with `sbt-pom-reader` was correlated with my starting to use `sbt-native-packager`. Excluding JDeb would have probably solved it for me, but it was a good to push me into convert that sub-project :-)

**Comment by metasim** [comment]
Things seem to be working OK with the 1.0.0 release of `sbt-native-packager`.

**Comment by dwalend** [comment]
I found a little time and tried updating to sbt 0.13.8, sbt-pom-reader 2.0.0, with addMavenResolverPlugin . I'm still getting the missing class def for the stack trace.

I'm not using sbt-native-packager. The complexity is all in maven. I'm hoping that doesn't matter much.

What kind of thing should I be looking for?

Thanks,

Dave

java.lang.NoClassDefFoundError: org/apache/maven/repository/internal/MavenServiceLocator
	at com.typesafe.sbt.pom.package$.newRepositorySystemImpl(package.scala:18)
	at com.typesafe.sbt.pom.MvnPomResolver$.<init>(MavenPomResolver.scala:18)
	at com.typesafe.sbt.pom.MvnPomResolver$.<clinit>(MavenPomResolver.scala)
	at com.typesafe.sbt.pom.package$.loadEffectivePom(package.scala:36)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:121)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:48)
	at com.typesafe.sbt.pom.PomBuild$class.projectDefinitions(PomBuild.scala:22)
	at MyBuild$.projectDefinitions(build.scala:3)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.repository.internal.MavenServiceLocator
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.typesafe.sbt.pom.package$.newRepositorySystemImpl(package.scala:18)
	at com.typesafe.sbt.pom.MvnPomResolver$.<init>(MavenPomResolver.scala:18)
	at com.typesafe.sbt.pom.MvnPomResolver$.<clinit>(MavenPomResolver.scala)
	at com.typesafe.sbt.pom.package$.loadEffectivePom(package.scala:36)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeProjectTree(MavenProjectHelper.scala:121)
	at com.typesafe.sbt.pom.MavenProjectHelper$.makeReactorProject(MavenProjectHelper.scala:48)
	at com.typesafe.sbt.pom.PomBuild$class.projectDefinitions(PomBuild.scala:22)
	at MyBuild$.projectDefinitions(build.scala:3)
	at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at sbt.Load$$anonfun$27.apply(Load.scala:436)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at sbt.Load$.loadUnit(Load.scala:436)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)

**Comment by metasim** [comment]
@dwalend Any chance you could dump the output of [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph) of the, um. project-project (?) so we can see what else might be causing the version clash? Now that I think about that, I'm not sure how you do that for the plugins. @jsuereth any tips on dumping the dependency list of the loaded plugins?

**Comment by dwalend** [comment]
Thanks for picking this up. SHRINE is open source, so you could potentially see everything. It's a sprawling project with some old tech and more than it's share of ugly. I'm trying to use sbt in one subproject before trying everywhere. Try https://open.med.harvard.edu/vvc/viewvc.cgi/shrine/trunk/code/steward/ as starting point if that will help.

**Comment by metasim** [comment]
@dwalend The `plugins.sbt` file references version `1.0.1`. Have you tried it with `2.0.0`?

**Comment by dwalend** [comment]
I got sbt-dependency-graph to show me a tree. (I gave up on the ascii graph after about two minutes.) it's got 1456 lines. What's a sane way to share it?

**Comment by metasim** [comment]
Create a gist?

**Comment by dwalend** [comment]
[gist of the .dot file](https://gist.github.com/dwalend/4d652ab1e5acc09eeae5)

Dot is an amazing relic. It's from 1985? Or 1859?

**Comment by metasim** [comment]
Gotta love the insanity of it!:


![dependencies-compile](https://cloud.githubusercontent.com/assets/131013/8087869/65ade5fa-0f6b-11e5-976b-e42e7b8f2b69.png)

**Comment by metasim** [comment]
@jsuereth Does this look suspicious to you?:
![screen shot 2015-06-10 at 12 37 00 pm](https://cloud.githubusercontent.com/assets/131013/8088222/bf720dee-0f6d-11e5-85ac-f047d7be3ab8.png)

**Comment by dwalend** [comment]
I'm glad to see it's that small. Someone made the svn trunk in early 2008, and that is r611. We're looking for out-of-date  maven-aether-providers ? (and I just spotted your update.)

**Comment by dwalend** [comment]
Those M2 versions are coming in from Maven's aether provider. That's pulled in by sbt-maven-resolver, maven-embedder, and sbt-pom-reader. M2 seems kinda sketchy to see. 

Have I got the wrong maven aether provider somehow? There's a 3.3.3 version available. However, it seems out-of-model to try to mess with that space. I didn't ask for either version.

What's the right fix?

**Comment by dwalend** [comment]
I do have addMavenResolverPlugin in the plugins.sbt

**Comment by metasim** [comment]
To be honest, at this point, I don't know. Might be worth just trying a different version to see.

**Comment by JoshRosen** [comment]
Could this issue be addressed by upgrading `sbt-pom-reader`'s own Maven and Aether dependencies? I noticed that this library is using a really old version of Maven. It seems that newer versions are neither source nor binary-compatible with the version used here, so it might be a bit of work to upgrade. Has anyone investigated this?

**Comment by metasim** [comment]
@JoshRosen What version would you recommend we try?

**Comment by metasim** [comment]
@JoshRosen @dwalend I have a draft version of the plugin with the Maven/Wagon/Aether dependencies updated. It passes all of its `scripted` tests, but I'm not convinced all cases are covered, so if you try it out I'd appreciate reports on any bugs you run into.

https://github.com/sbt/sbt-pom-reader/tree/release/2.1.0-RC1
https://bintray.com/sbt/sbt-plugin-releases/sbt-pom-reader/2.1.0-RC1

**Comment by metasim** [comment]
FYI, RC2 is available (had to back off Maven library version to 3.2.2)

https://github.com/sbt/sbt-pom-reader/tree/release/2.1.0-RC
https://bintray.com/sbt/sbt-plugin-releases/sbt-pom-reader/2.1.0-RC2

**Comment by dwalend** [comment]
Got a chance to try RC2 today. (Sorry about taking so long.) Looks like you've fixed this bug, at least for SHRINE (https://open.med.harvard.edu/stash/projects/SHRINE/repos/shrine/browse?at=refs%2Fheads%2Fdevelop It's currently finding 1887 errors, looks like sbt-pom-reader is missing test dependencies.)

Thanks,

Dave

**Comment by jvican** [comment]
For an updated version of this, see https://github.com/scalacenter/sbt-pom-reader/commit/f13c8531a77d13d19bb64ae667c9926abae4ca5e and its commit message.
